type Flag is Type:
  Off{}
  On{}
def f0() -> Flag:
  Off{}
def f1() -> Flag:
  Off{}
def f2() -> Flag:
  Off{}
def f3() -> Flag:
  Off{}
def f4() -> Flag:
  Off{}
def f5() -> Flag:
  Off{}
def f6() -> Flag:
  Off{}
def f7() -> Flag:
  Off{}
def f8() -> Flag:
  Off{}
def f9() -> Flag:
  Off{}
def f10() -> Flag:
  Off{}
def f11() -> Flag:
  Off{}
def f12() -> Flag:
  Off{}
def f13() -> Flag:
  Off{}
def f14() -> Flag:
  Off{}
def f15() -> Flag:
  Off{}
def f16() -> Flag:
  Off{}
def f17() -> Flag:
  Off{}
def f18() -> Flag:
  Off{}
def f19() -> Flag:
  Off{}
def f20() -> Flag:
  Off{}
def f21() -> Flag:
  Off{}
def f22() -> Flag:
  Off{}
def f23() -> Flag:
  Off{}
def f24() -> Flag:
  Off{}
def f25() -> Flag:
  Off{}
def f26() -> Flag:
  Off{}
def f27() -> Flag:
  Off{}
def f28() -> Flag:
  Off{}
def f29() -> Flag:
  Off{}
def f30() -> Flag:
  Off{}
def f31() -> Flag:
  Off{}
def f32() -> Flag:
  Off{}
def f33() -> Flag:
  Off{}
def f34() -> Flag:
  Off{}
def f35() -> Flag:
  Off{}
def f36() -> Flag:
  Off{}
def f37() -> Flag:
  Off{}
def f38() -> Flag:
  Off{}
def f39() -> Flag:
  Off{}
def f40() -> Flag:
  Off{}
def f41() -> Flag:
  Off{}
def f42() -> Flag:
  Off{}
def f43() -> Flag:
  Off{}
def f44() -> Flag:
  Off{}
def f45() -> Flag:
  Off{}
def f46() -> Flag:
  Off{}
def f47() -> Flag:
  Off{}
def f48() -> Flag:
  Off{}
def f49() -> Flag:
  Off{}
def f50() -> Flag:
  Off{}
def f51() -> Flag:
  Off{}
def f52() -> Flag:
  Off{}
def f53() -> Flag:
  Off{}
def f54() -> Flag:
  Off{}
def f55() -> Flag:
  Off{}
def f56() -> Flag:
  Off{}
def f57() -> Flag:
  Off{}
def f58() -> Flag:
  Off{}
def f59() -> Flag:
  Off{}
def f60() -> Flag:
  Off{}
def f61() -> Flag:
  Off{}
def f62() -> Flag:
  Off{}
def f63() -> Flag:
  Off{}
def f64() -> Flag:
  Off{}
def f65() -> Flag:
  Off{}
def f66() -> Flag:
  Off{}
def f67() -> Flag:
  Off{}
def f68() -> Flag:
  Off{}
def f69() -> Flag:
  Off{}
def f70() -> Flag:
  Off{}
def f71() -> Flag:
  Off{}
def f72() -> Flag:
  Off{}
def f73() -> Flag:
  Off{}
def f74() -> Flag:
  Off{}
def f75() -> Flag:
  Off{}
def f76() -> Flag:
  Off{}
def f77() -> Flag:
  Off{}
def f78() -> Flag:
  Off{}
def f79() -> Flag:
  Off{}
def f80() -> Flag:
  Off{}
def f81() -> Flag:
  Off{}
def f82() -> Flag:
  Off{}
def f83() -> Flag:
  Off{}
def f84() -> Flag:
  Off{}
def f85() -> Flag:
  Off{}
def f86() -> Flag:
  Off{}
def f87() -> Flag:
  Off{}
def f88() -> Flag:
  Off{}
def f89() -> Flag:
  Off{}
def f90() -> Flag:
  Off{}
def f91() -> Flag:
  Off{}
def f92() -> Flag:
  Off{}
def f93() -> Flag:
  Off{}
def f94() -> Flag:
  Off{}
def f95() -> Flag:
  Off{}
def f96() -> Flag:
  Off{}
def f97() -> Flag:
  Off{}
def f98() -> Flag:
  Off{}
def f99() -> Flag:
  Off{}
def f100() -> Flag:
  Off{}
def f101() -> Flag:
  Off{}
def f102() -> Flag:
  Off{}
def f103() -> Flag:
  Off{}
def f104() -> Flag:
  Off{}
def f105() -> Flag:
  Off{}
def f106() -> Flag:
  Off{}
def f107() -> Flag:
  Off{}
def f108() -> Flag:
  Off{}
def f109() -> Flag:
  Off{}
def f110() -> Flag:
  Off{}
def f111() -> Flag:
  Off{}
def f112() -> Flag:
  Off{}
def f113() -> Flag:
  Off{}
def f114() -> Flag:
  Off{}
def f115() -> Flag:
  Off{}
def f116() -> Flag:
  Off{}
def f117() -> Flag:
  Off{}
def f118() -> Flag:
  Off{}
def f119() -> Flag:
  Off{}
def f120() -> Flag:
  Off{}
def f121() -> Flag:
  Off{}
def f122() -> Flag:
  Off{}
def f123() -> Flag:
  Off{}
def f124() -> Flag:
  Off{}
def f125() -> Flag:
  Off{}
def f126() -> Flag:
  Off{}
def f127() -> Flag:
  Off{}
def f128() -> Flag:
  On{}
def main() -> Flag:
  f128()
