"""Fixed observation specification, written independently of either scope source.

Expected records are generated by position, not by replaying the implementation's
list traversal. Every token span, metadata field, and exercised term field is
observed. The fixture's supported term shapes are Value, Reference, Construct;
unexpected shapes must fail the exact observation comparison.
"""
SIZES = (0, 1, 7, 16, 64, 256, 1024)
CASES = ('empty', 'missing', 'first', 'middle', 'last', 'duplicate')
REPLACEMENT = ('C(replacement,9001,9002,9003,9004;701;702;'
               'P(field,8001,8002,8003,8004;2;703);'
               'R(argument,7001,7002,7003,7004;704;705))')


def token(i):
    return f'b{i},{i},{i+2},{i+3},{i+4}'


def original_known(i):
    return (
        'None',
        f'Some(V({token(i+100)};{i+200};{i+300}))',
        f'Some(R({token(i+400)};{i+500};{i+600}))',
        f'Some({REPLACEMENT})',
    )[i % 4]


def expected(n):
    lines = []
    for case in CASES:
        for operation in ('refine', 'replace'):
            lines.append(f'{operation}/{case}')
            for i in range(0 if case == 'empty' else n):
                duplicate = case == 'duplicate' and i % 3 == 0
                identity = 7 if duplicate else i + 10
                selected = (case == 'first' and i == 0 or
                            case == 'middle' and i == n // 2 or
                            case == 'last' and i == n - 1 or duplicate)
                value = original_known(i)
                if selected:
                    value = (f'Some(V({token(i)};{i+20};909))' if operation == 'refine'
                             else f'Some({REPLACEMENT})')
                lines.append(f'{token(i)}|{identity}|{i%3}|{i+20}|'
                             f'{str(i%2 == 0).lower()}|{value}')
            lines.append('END')
    return '\n'.join(lines) + '\n'


# Literal anchors guard the observation recipe's tokens, metadata, and term shape.
assert token(0) == 'b0,0,2,3,4'
assert original_known(1) == 'Some(V(b101,101,103,104,105;201;301))'
assert original_known(2) == 'Some(R(b402,402,404,405,406;502;602))'
assert ('b0,0,2,3,4|10|0|20|true|Some(V(b0,0,2,3,4;20;909))'
        in expected(1))
