type Tag is Type:
  T0{}
  T1{}
  T2{}
  T3{}
  T4{}
  T5{}
  T6{}
  T7{}
  T8{}
  T9{}
  T10{}
  T11{}
  T12{}
  T13{}
  T14{}
  T15{}
  T16{}
  T17{}
  T18{}
  T19{}
  T20{}
  T21{}
  T22{}
  T23{}
  T24{}
  T25{}
  T26{}
  T27{}
  T28{}
  T29{}
  T30{}
  T31{}
  T32{}
  T33{}
  T34{}
  T35{}
  T36{}
  T37{}
  T38{}
  T39{}
  T40{}
  T41{}
  T42{}
  T43{}
  T44{}
  T45{}
  T46{}
  T47{}
  T48{}
  T49{}
  T50{}
  T51{}
  T52{}
  T53{}
  T54{}
  T55{}
  T56{}
  T57{}
  T58{}
  T59{}
  T60{}
  T61{}
  T62{}
  T63{}
  T64{}
  T65{}
  T66{}
  T67{}
  T68{}
  T69{}
  T70{}
  T71{}
  T72{}
  T73{}
  T74{}
  T75{}
  T76{}
  T77{}
  T78{}
  T79{}
  T80{}
  T81{}
  T82{}
  T83{}
  T84{}
  T85{}
  T86{}
  T87{}
  T88{}
  T89{}
  T90{}
  T91{}
  T92{}
  T93{}
  T94{}
  T95{}
  T96{}
  T97{}
  T98{}
  T99{}
  T100{}
  T101{}
  T102{}
  T103{}
  T104{}
  T105{}
  T106{}
  T107{}
  T108{}
  T109{}
  T110{}
  T111{}
  T112{}
  T113{}
  T114{}
  T115{}
  T116{}
  T117{}
  T118{}
  T119{}
  T120{}
  T121{}
  T122{}
  T123{}
  T124{}
  T125{}
  T126{}
  T127{}
  T128{}
  T129{}
  T130{}
  T131{}
  T132{}
  T133{}
  T134{}
  T135{}
  T136{}
  T137{}
  T138{}
  T139{}
  T140{}
  T141{}
  T142{}
  T143{}
  T144{}
  T145{}
  T146{}
  T147{}
  T148{}
  T149{}
  T150{}
  T151{}
  T152{}
  T153{}
  T154{}
  T155{}
  T156{}
  T157{}
  T158{}
  T159{}
  T160{}
  T161{}
  T162{}
  T163{}
  T164{}
  T165{}
  T166{}
  T167{}
  T168{}
  T169{}
  T170{}
  T171{}
  T172{}
  T173{}
  T174{}
  T175{}
  T176{}
  T177{}
  T178{}
  T179{}
  T180{}
  T181{}
  T182{}
  T183{}
  T184{}
  T185{}
  T186{}
  T187{}
  T188{}
  T189{}
  T190{}
  T191{}
  T192{}
  T193{}
  T194{}
  T195{}
  T196{}
  T197{}
  T198{}
  T199{}
  T200{}
  T201{}
  T202{}
  T203{}
  T204{}
  T205{}
  T206{}
  T207{}
  T208{}
  T209{}
  T210{}
  T211{}
  T212{}
  T213{}
  T214{}
  T215{}
  T216{}
  T217{}
  T218{}
  T219{}
  T220{}
  T221{}
  T222{}
  T223{}
  T224{}
  T225{}
  T226{}
  T227{}
  T228{}
  T229{}
  T230{}
  T231{}
  T232{}
  T233{}
  T234{}
  T235{}
  T236{}
  T237{}
  T238{}
  T239{}
  T240{}
  T241{}
  T242{}
  T243{}
  T244{}
  T245{}
  T246{}
  T247{}
  T248{}
  T249{}
  T250{}
  T251{}
  T252{}
  T253{}
  T254{}

def rotate(x: Tag) -> Tag:
  match x:
    case T0{}: T1{}
    case T1{}: T2{}
    case T2{}: T3{}
    case T3{}: T4{}
    case T4{}: T5{}
    case T5{}: T6{}
    case T6{}: T7{}
    case T7{}: T8{}
    case T8{}: T9{}
    case T9{}: T10{}
    case T10{}: T11{}
    case T11{}: T12{}
    case T12{}: T13{}
    case T13{}: T14{}
    case T14{}: T15{}
    case T15{}: T16{}
    case T16{}: T17{}
    case T17{}: T18{}
    case T18{}: T19{}
    case T19{}: T20{}
    case T20{}: T21{}
    case T21{}: T22{}
    case T22{}: T23{}
    case T23{}: T24{}
    case T24{}: T25{}
    case T25{}: T26{}
    case T26{}: T27{}
    case T27{}: T28{}
    case T28{}: T29{}
    case T29{}: T30{}
    case T30{}: T31{}
    case T31{}: T32{}
    case T32{}: T33{}
    case T33{}: T34{}
    case T34{}: T35{}
    case T35{}: T36{}
    case T36{}: T37{}
    case T37{}: T38{}
    case T38{}: T39{}
    case T39{}: T40{}
    case T40{}: T41{}
    case T41{}: T42{}
    case T42{}: T43{}
    case T43{}: T44{}
    case T44{}: T45{}
    case T45{}: T46{}
    case T46{}: T47{}
    case T47{}: T48{}
    case T48{}: T49{}
    case T49{}: T50{}
    case T50{}: T51{}
    case T51{}: T52{}
    case T52{}: T53{}
    case T53{}: T54{}
    case T54{}: T55{}
    case T55{}: T56{}
    case T56{}: T57{}
    case T57{}: T58{}
    case T58{}: T59{}
    case T59{}: T60{}
    case T60{}: T61{}
    case T61{}: T62{}
    case T62{}: T63{}
    case T63{}: T64{}
    case T64{}: T65{}
    case T65{}: T66{}
    case T66{}: T67{}
    case T67{}: T68{}
    case T68{}: T69{}
    case T69{}: T70{}
    case T70{}: T71{}
    case T71{}: T72{}
    case T72{}: T73{}
    case T73{}: T74{}
    case T74{}: T75{}
    case T75{}: T76{}
    case T76{}: T77{}
    case T77{}: T78{}
    case T78{}: T79{}
    case T79{}: T80{}
    case T80{}: T81{}
    case T81{}: T82{}
    case T82{}: T83{}
    case T83{}: T84{}
    case T84{}: T85{}
    case T85{}: T86{}
    case T86{}: T87{}
    case T87{}: T88{}
    case T88{}: T89{}
    case T89{}: T90{}
    case T90{}: T91{}
    case T91{}: T92{}
    case T92{}: T93{}
    case T93{}: T94{}
    case T94{}: T95{}
    case T95{}: T96{}
    case T96{}: T97{}
    case T97{}: T98{}
    case T98{}: T99{}
    case T99{}: T100{}
    case T100{}: T101{}
    case T101{}: T102{}
    case T102{}: T103{}
    case T103{}: T104{}
    case T104{}: T105{}
    case T105{}: T106{}
    case T106{}: T107{}
    case T107{}: T108{}
    case T108{}: T109{}
    case T109{}: T110{}
    case T110{}: T111{}
    case T111{}: T112{}
    case T112{}: T113{}
    case T113{}: T114{}
    case T114{}: T115{}
    case T115{}: T116{}
    case T116{}: T117{}
    case T117{}: T118{}
    case T118{}: T119{}
    case T119{}: T120{}
    case T120{}: T121{}
    case T121{}: T122{}
    case T122{}: T123{}
    case T123{}: T124{}
    case T124{}: T125{}
    case T125{}: T126{}
    case T126{}: T127{}
    case T127{}: T128{}
    case T128{}: T129{}
    case T129{}: T130{}
    case T130{}: T131{}
    case T131{}: T132{}
    case T132{}: T133{}
    case T133{}: T134{}
    case T134{}: T135{}
    case T135{}: T136{}
    case T136{}: T137{}
    case T137{}: T138{}
    case T138{}: T139{}
    case T139{}: T140{}
    case T140{}: T141{}
    case T141{}: T142{}
    case T142{}: T143{}
    case T143{}: T144{}
    case T144{}: T145{}
    case T145{}: T146{}
    case T146{}: T147{}
    case T147{}: T148{}
    case T148{}: T149{}
    case T149{}: T150{}
    case T150{}: T151{}
    case T151{}: T152{}
    case T152{}: T153{}
    case T153{}: T154{}
    case T154{}: T155{}
    case T155{}: T156{}
    case T156{}: T157{}
    case T157{}: T158{}
    case T158{}: T159{}
    case T159{}: T160{}
    case T160{}: T161{}
    case T161{}: T162{}
    case T162{}: T163{}
    case T163{}: T164{}
    case T164{}: T165{}
    case T165{}: T166{}
    case T166{}: T167{}
    case T167{}: T168{}
    case T168{}: T169{}
    case T169{}: T170{}
    case T170{}: T171{}
    case T171{}: T172{}
    case T172{}: T173{}
    case T173{}: T174{}
    case T174{}: T175{}
    case T175{}: T176{}
    case T176{}: T177{}
    case T177{}: T178{}
    case T178{}: T179{}
    case T179{}: T180{}
    case T180{}: T181{}
    case T181{}: T182{}
    case T182{}: T183{}
    case T183{}: T184{}
    case T184{}: T185{}
    case T185{}: T186{}
    case T186{}: T187{}
    case T187{}: T188{}
    case T188{}: T189{}
    case T189{}: T190{}
    case T190{}: T191{}
    case T191{}: T192{}
    case T192{}: T193{}
    case T193{}: T194{}
    case T194{}: T195{}
    case T195{}: T196{}
    case T196{}: T197{}
    case T197{}: T198{}
    case T198{}: T199{}
    case T199{}: T200{}
    case T200{}: T201{}
    case T201{}: T202{}
    case T202{}: T203{}
    case T203{}: T204{}
    case T204{}: T205{}
    case T205{}: T206{}
    case T206{}: T207{}
    case T207{}: T208{}
    case T208{}: T209{}
    case T209{}: T210{}
    case T210{}: T211{}
    case T211{}: T212{}
    case T212{}: T213{}
    case T213{}: T214{}
    case T214{}: T215{}
    case T215{}: T216{}
    case T216{}: T217{}
    case T217{}: T218{}
    case T218{}: T219{}
    case T219{}: T220{}
    case T220{}: T221{}
    case T221{}: T222{}
    case T222{}: T223{}
    case T223{}: T224{}
    case T224{}: T225{}
    case T225{}: T226{}
    case T226{}: T227{}
    case T227{}: T228{}
    case T228{}: T229{}
    case T229{}: T230{}
    case T230{}: T231{}
    case T231{}: T232{}
    case T232{}: T233{}
    case T233{}: T234{}
    case T234{}: T235{}
    case T235{}: T236{}
    case T236{}: T237{}
    case T237{}: T238{}
    case T238{}: T239{}
    case T239{}: T240{}
    case T240{}: T241{}
    case T241{}: T242{}
    case T242{}: T243{}
    case T243{}: T244{}
    case T244{}: T245{}
    case T245{}: T246{}
    case T246{}: T247{}
    case T247{}: T248{}
    case T248{}: T249{}
    case T249{}: T250{}
    case T250{}: T251{}
    case T251{}: T252{}
    case T252{}: T253{}
    case T253{}: T254{}
    case T254{}: T0{}

def main() -> Tag:
  rotate(T254{})
