(module
  (import "knot_io" "args" (func $args (param i32)))
  (import "knot_io" "print" (func $print (param i32 i32)))
  (import "knot_io" "open" (func $open (param i32 i32 i32 i32 i32)))
  (import "knot_io" "read" (func $read (param i32 i32 i32)))
  (import "knot_io" "read_bytes" (func $read_bytes (param i32 i32 i32)))
  (import "knot_io" "path_identity" (func $path_identity (param i32 i32 i32)))
  (import "knot_io" "close" (func $close (param i32)))
  (import "knot_io" "exhausted" (func $exhausted (param i32)))
  (memory (export "memory") 1 2048)
  (global $heap (mut i32) (i32.const 8192))
  (data (i32.const 128) "0123456789abcdef")
  ;; @DATA@
  (func $alloc (export "knot_alloc") (param $n i32) (result i32)
    (local $p i32) (local $end i32) (local $pages i32)
    ;; @ALLOC@
    (local.set $p (global.get $heap))
    (if (i32.gt_u (local.get $n) (i32.sub (i32.const 134217728) (local.get $p)))
      (then (call $exhausted (i32.const 2))))
    (local.set $end (i32.add (local.get $p) (local.get $n)))
    (local.set $pages (i32.shr_u (i32.add (local.get $end) (i32.const 65535)) (i32.const 16)))
    (if (i32.gt_u (local.get $pages) (memory.size))
      (then
        (if (i32.eq (memory.grow (i32.sub (local.get $pages) (memory.size))) (i32.const -1))
          (then (call $exhausted (i32.const 2))))))
    (global.set $heap (local.get $end))
    (local.get $p))
  (func $digit (param $n i32) (result i32)
    (i32.load8_u (i32.add (i32.const 128) (i32.and (local.get $n) (i32.const 15)))))
  (func $word (param $p i32) (param $n i32)
    (local $i i32)
    (loop $next
      (i32.store8 (i32.add (local.get $p) (local.get $i))
        (call $digit (i32.shr_u (local.get $n)
          (i32.sub (i32.const 28) (i32.mul (local.get $i) (i32.const 4))))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $next (i32.lt_u (local.get $i) (i32.const 8)))))
  ;; Observe errno, value and every returned byte without text conversion.
  (func $dump
    (local $p i32) (local $n i32) (local $q i32) (local $i i32) (local $b i32)
    (local.set $p (i32.load (i32.const 72)))
    (local.set $n (i32.load (i32.const 76)))
    (if (i32.and (i32.eqz (local.get $n)) (i32.ne (local.get $p) (i32.const 0)))
      (then (unreachable)))
    (local.set $q (call $alloc (i32.add (i32.const 18) (i32.mul (local.get $n) (i32.const 2)))))
    (call $word (local.get $q) (i32.load (i32.const 64)))
    (i32.store8 offset=8 (local.get $q) (i32.const 32))
    (call $word (i32.add (local.get $q) (i32.const 9)) (i32.load (i32.const 68)))
    (i32.store8 offset=17 (local.get $q) (i32.const 32))
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $b (i32.load8_u (i32.add (local.get $p) (local.get $i))))
      (i32.store8 (i32.add (i32.add (local.get $q) (i32.const 18))
        (i32.mul (local.get $i) (i32.const 2)))
        (call $digit (i32.shr_u (local.get $b) (i32.const 4))))
      (i32.store8 (i32.add (i32.add (local.get $q) (i32.const 19))
        (i32.mul (local.get $i) (i32.const 2))) (call $digit (local.get $b)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $next)))
    (call $print (local.get $q) (i32.add (i32.const 18) (i32.mul (local.get $n) (i32.const 2)))))
  (func (export "knot_main")
    ;; @BODY@
  ))
