;; Test interpreter for defunctionalized IO descriptions, not a Bend compiler.
(module
  (import "knot_io" "args" (func $args (param i32)))
  (import "knot_io" "print" (func $print (param i32 i32)))
  (import "knot_io" "die" (func $die (param i32 i32 i32)))
  (import "knot_io" "open" (func $open (param i32 i32 i32 i32 i32)))
  (import "knot_io" "read" (func $read (param i32 i32 i32)))
  (import "knot_io" "write_bytes" (func $write (param i32 i32 i32 i32 i32)))
  (import "knot_io" "close" (func $close (param i32)))
  (import "knot_io" "exhausted" (func $exhausted (param i32)))
  (memory (export "memory") @@PAGES@@ 2048)
  (global $bump (mut i32) (i32.const @@HEAP@@))
  (global $out (mut i32) (i32.const 0))
  (global $size (mut i32) (i32.const 0))
  (global $cursor (mut i32) (i32.const 0))
  (global $value (mut i32) (i32.const 0))
  (data (i32.const 128) "Fail DoneDone chars  last argc ")
  (data (i32.const 4096) "@@DATA@@")

  (func $alloc (export "knot_alloc") (param $n i32) (result i32)
    (local $p i32) (local $end i32) (local $pages i32)
    (local.set $p (global.get $bump))
    (if (i32.gt_u (local.get $n) (i32.sub (i32.const 134217724) (local.get $p)))
      (then (call $exhausted (i32.const 2)) (unreachable)))
    (local.set $end (i32.and (i32.add (i32.add (local.get $p) (local.get $n)) (i32.const 3)) (i32.const -4)))
    (local.set $pages (i32.shr_u (i32.add (local.get $end) (i32.const 65535)) (i32.const 16)))
    (if (i32.gt_u (local.get $pages) (memory.size))
      (then (if (i32.eq (memory.grow (i32.sub (local.get $pages) (memory.size))) (i32.const -1))
        (then (call $exhausted (i32.const 2)) (unreachable)))))
    (global.set $bump (local.get $end))
    (local.get $p))

  (func $append (param $p i32) (param $n i32)
    (if (i32.gt_u (local.get $n) (i32.sub (i32.const 1048576) (global.get $size)))
      (then (call $exhausted (i32.const 2)) (unreachable)))
    (memory.copy (i32.add (global.get $out) (global.get $size)) (local.get $p) (local.get $n))
    (global.set $size (i32.add (global.get $size) (local.get $n))))
  (func $char (param $c i32)
    (i32.store8 (i32.const 1000) (local.get $c))
    (call $append (i32.const 1000) (i32.const 1)))
  (func $num (param $n i32)
    (local $p i32)
    (local.set $p (i32.const 1040))
    (loop $digits
      (local.set $p (i32.sub (local.get $p) (i32.const 1)))
      (i32.store8 (local.get $p) (i32.add (i32.const 48) (i32.rem_u (local.get $n) (i32.const 10))))
      (local.set $n (i32.div_u (local.get $n) (i32.const 10)))
      (br_if $digits (local.get $n)))
    (call $append (local.get $p) (i32.sub (i32.const 1040) (local.get $p))))
  (func $flush (call $print (global.get $out) (global.get $size)))

  ;; Inputs here are canonical UTF-8 returned by the host; decode scalar values.
  (func $scalar (result i32)
    (local $c i32) (local $n i32) (local $v i32)
    (local.set $c (i32.load8_u (global.get $cursor)))
    (global.set $cursor (i32.add (global.get $cursor) (i32.const 1)))
    (if (i32.lt_u (local.get $c) (i32.const 128)) (then (return (local.get $c))))
    (if (i32.lt_u (local.get $c) (i32.const 224))
      (then (local.set $n (i32.const 1)) (local.set $v (i32.and (local.get $c) (i32.const 31))))
      (else (if (i32.lt_u (local.get $c) (i32.const 240))
        (then (local.set $n (i32.const 2)) (local.set $v (i32.and (local.get $c) (i32.const 15))))
        (else (local.set $n (i32.const 3)) (local.set $v (i32.and (local.get $c) (i32.const 7)))))))
    (loop $tail
      (local.set $v (i32.or (i32.shl (local.get $v) (i32.const 6))
        (i32.and (i32.load8_u (global.get $cursor)) (i32.const 63))))
      (global.set $cursor (i32.add (global.get $cursor) (i32.const 1)))
      (local.set $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $tail (local.get $n)))
    (local.get $v))
  (func $codes (param $p i32) (param $n i32)
    (global.set $cursor (local.get $p))
    (block $done (loop $each
      (br_if $done (i32.ge_u (global.get $cursor) (i32.add (local.get $p) (local.get $n))))
      (call $char (i32.const 32)) (call $num (call $scalar)) (br $each))))
  (func $summary (param $p i32) (param $n i32)
    (local $count i32) (local $last i32)
    (global.set $cursor (local.get $p))
    (block $done (loop $each
      (br_if $done (i32.ge_u (global.get $cursor) (i32.add (local.get $p) (local.get $n))))
      (local.set $last (call $scalar))
      (local.set $count (i32.add (local.get $count) (i32.const 1))) (br $each)))
    (call $append (i32.const 142) (i32.const 6)) (call $num (local.get $count))
    (call $append (i32.const 148) (i32.const 6)) (call $num (local.get $last)))
  (func $errno
    (call $num (i32.load (i32.const 64))) (call $char (i32.const 32))
    (call $append (i32.load (i32.const 72)) (i32.load (i32.const 76))))

  ;; Report nodes are pure fixture continuations followed by IO.print.
  (func $report (param $mode i32) (param $p i32) (param $n i32)
    (global.set $size (i32.const 0)) (call $append (local.get $p) (local.get $n))
    (if (i32.eq (local.get $mode) (i32.const 4))
      (then (call $num (global.get $value)) (call $flush) (return)))
    (if (i32.load (i32.const 64))
      (then
        (if (i32.eq (local.get $mode) (i32.const 1)) (then (call $char (i32.const 32))))
        (call $append (i32.const 128) (i32.const 5)) (call $errno))
      (else
        (if (i32.eq (local.get $mode) (i32.const 0))
          (then (call $append (i32.load (i32.const 72)) (i32.load (i32.const 76)))))
        (if (i32.eq (local.get $mode) (i32.const 1))
          (then (call $codes (i32.load (i32.const 72)) (i32.load (i32.const 76)))))
        (if (i32.eq (local.get $mode) (i32.const 2))
          (then (call $summary (i32.load (i32.const 72)) (i32.load (i32.const 76)))))
        (if (i32.eq (local.get $mode) (i32.const 3))
          (then (call $append (i32.const 133) (i32.const 4))))
        (if (i32.eq (local.get $mode) (i32.const 6))
          (then (call $append (i32.const 137) (i32.const 5))
            (call $append (i32.load (i32.const 72)) (i32.load (i32.const 76)))))))
    (call $flush))
  (func $echo
    (local $i i32) (local $table i32) (local $count i32) (local $p i32) (local $n i32)
    (local.set $table (i32.load (i32.const 72))) (local.set $count (i32.load (i32.const 68)))
    (block $done (loop $each
      (br_if $done (i32.ge_u (local.get $i) (local.get $count)))
      (local.set $p (i32.load (i32.add (local.get $table) (i32.mul (local.get $i) (i32.const 8)))))
      (local.set $n (i32.load offset=4 (i32.add (local.get $table) (i32.mul (local.get $i) (i32.const 8)))))
      (global.set $size (i32.const 0)) (call $char (i32.const 91))
      (call $append (local.get $p) (local.get $n)) (call $char (i32.const 93))
      (call $codes (local.get $p) (local.get $n)) (call $flush)
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $each)))
    (global.set $size (i32.const 0)) (call $append (i32.const 154) (i32.const 5))
    (call $num (local.get $count)) (call $flush))

  (func (export "knot_main")
    (local $pc i32) (local $tag i32) (local $a i32) (local $b i32)
    (local $stack i32) (local $sp i32) (local $steps i32) (local $handle i32)
    (local $p i32) (local $i i32) (local $v i32) (local $invalid i32)
    (global.set $out (call $alloc (i32.const 1048576)))
    (local.set $stack (call $alloc (i32.const 800008)))
    (local.set $pc (i32.const @@ROOT@@))
    (loop $step
      (local.set $steps (i32.add (local.get $steps) (i32.const 1)))
      (if (i32.gt_u (local.get $steps) (i32.const @@STEPS@@))
        (then (call $exhausted (i32.const 1)) (unreachable)))
      (local.set $tag (i32.load (local.get $pc)))
      (local.set $a (i32.load offset=4 (local.get $pc)))
      (local.set $b (i32.load offset=8 (local.get $pc)))
      (if (i32.eq (local.get $tag) (i32.const 1))
        (then
          (if (i32.ge_u (local.get $sp) (i32.const 800008))
            (then (call $exhausted (i32.const 2)) (unreachable)))
          (i32.store (i32.add (local.get $stack) (local.get $sp)) (local.get $b))
          (local.set $sp (i32.add (local.get $sp) (i32.const 4)))
          (local.set $pc (local.get $a)) (br $step)))
      (if (i32.eq (local.get $tag) (i32.const 0)) (then (global.set $value (local.get $a))))
      (if (i32.eq (local.get $tag) (i32.const 4))
        (then (global.set $value (i32.add (global.get $value) (local.get $a)))))
      (if (i32.eq (local.get $tag) (i32.const 3))
        (then (call $die (local.get $a) (local.get $b) (i32.load offset=12 (local.get $pc))) (unreachable)))
      (if (i32.eq (local.get $tag) (i32.const 5))
        (then (call $report (local.get $a) (local.get $b) (i32.load offset=12 (local.get $pc)))))
      (if (i32.eq (local.get $tag) (i32.const 7)) (then (call $echo)))
      (if (i32.eq (local.get $tag) (i32.const 6))
        (then (if (i32.load (i32.const 64)) (then
          (global.set $size (i32.const 0))
          (if (local.get $b) (then
            (call $append (local.get $b) (i32.load offset=12 (local.get $pc)))
            (call $num (i32.load (i32.const 64))) (call $char (i32.const 9))))
          (call $append (i32.load (i32.const 72)) (i32.load (i32.const 76)))
          (call $die (select (i32.load (i32.const 64)) (local.get $a) (i32.eqz (local.get $a)))
            (global.get $out) (global.get $size)) (unreachable)))))
      (if (i32.eq (local.get $tag) (i32.const 8))
        (then (if (i32.load (i32.const 64))
          (then (local.set $pc (local.get $a)) (br $step))
          (else (local.set $pc (local.get $b)) (br $step)))))
      (if (i32.eq (local.get $tag) (i32.const 2)) (then
        (if (i32.gt_u (local.get $a) (i32.const 5)) (then (unreachable)))
        (if (i32.eq (local.get $a) (i32.const 0)) (then (call $args (i32.const 64))))
        (if (i32.eq (local.get $a) (i32.const 1))
          (then (call $print (local.get $b) (i32.load offset=12 (local.get $pc)))))
        (if (i32.eq (local.get $a) (i32.const 2)) (then
          (call $open (local.get $b) (i32.load offset=12 (local.get $pc))
            (i32.load offset=16 (local.get $pc)) (i32.load offset=20 (local.get $pc)) (i32.const 64))
          (if (i32.eqz (i32.load (i32.const 64))) (then (local.set $handle (i32.load (i32.const 68)))))))
        (if (i32.eq (local.get $a) (i32.const 3))
          (then (call $read (local.get $handle) (local.get $b) (i32.const 64))))
        (if (i32.eq (local.get $a) (i32.const 4)) (then
          (local.set $p (call $alloc (i32.load offset=12 (local.get $pc))))
          (local.set $i (i32.const 0)) (local.set $invalid (i32.const 0))
          (block $packed (loop $pack
            (br_if $packed (i32.ge_u (local.get $i) (i32.load offset=12 (local.get $pc))))
            (local.set $v (i32.load (i32.add (local.get $b) (i32.mul (local.get $i) (i32.const 4)))))
            (local.set $invalid (i32.or (local.get $invalid) (i32.shr_u (local.get $v) (i32.const 8))))
            (i32.store8 (i32.add (local.get $p) (local.get $i)) (local.get $v))
            (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $pack)))
          (call $write (local.get $handle) (local.get $p) (i32.load offset=12 (local.get $pc))
            (local.get $invalid) (i32.const 64))))
        (if (i32.eq (local.get $a) (i32.const 5)) (then (call $close (local.get $handle))))))
      (if (i32.gt_u (local.get $tag) (i32.const 8)) (then (unreachable)))
      (if (i32.eqz (local.get $sp)) (then (return)))
      (local.set $sp (i32.sub (local.get $sp) (i32.const 4)))
      (local.set $pc (i32.load (i32.add (local.get $stack) (local.get $sp))))
      (br $step)))
)
