type T is Type:
  K{}
def wide(_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,_: T,x: T) -> T:
  x
def main() -> T:
  f = wide(K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{},K{})
  f(K{})
