"""C3 frozen-and-owned: frozen and owned artifacts, and the history, between the effective base and head.

Rules (DESIGN 3.3). Authorization is read from main, never from the branch and never from a commit message.

  R1 out-of-scope-edit        a changed path outside the manifest's owns/appends (needs a declared `owns`)
  R2 shared-file-shape        a shared file changed by more than its allowed additive shape
  R3 frozen-edit              a frozen path differs from base with no authorized entry
  R4 assertion-weakened       a base-present gate script lost or loosened an assertion, or a mutant/control list shrank
  R5 coverage-dropped         a count or name list in a base-present receipt shrank
  R6 frozen-row-changed       a row of a declared frozen data file changed (additions are allowed)
  R7 freeze-order / provenance-mismatch
  R8 generator-not-reproducible   (declared generators only)
  R9 normalized-comparison
  R10 history lints (trailer, red wording, census approval summary, mixed-gate commit)
  R11 red-tip                 census:test / census --check fail at head
"""
from __future__ import annotations

import ast
import difflib
import hashlib
import json
import re

from lib import diffs
from lib import gates as gates_lib
from lib import globs
from lib import receipts as R
from lib.model import CheckResult, Condition
from lib.runner import Check

ID = 'C3'
EXPECTATION_LIKE = re.compile(r'(?:^|/)(?:expectations?|cases|regressions|bounds|fixtures)[^/]*\.json$|\.plan\.json$|'
                              r'(?:^|/)model-controls[^/]*$')
GATE_SCRIPT = re.compile(r'^(?:tests|research)/.+/(?:check[^/]*\.py|trust\.ts|host-check\.py)$|^scripts/gates/[^/]+\.py$')
ASSERT_LINE = re.compile(r'^\s*(?:require\(|assert\b|raise\b|self\.assert\w*\()')
COVERAGE_KEYS = ('mutants', 'fixtures', 'controls', 'rejects', 'observations', 'goldens', 'invocations', 'boundaries',
                 'budgets', 'bounds', 'host_boundaries')
LIST_NAMES = re.compile(r'^(?:MUTANTS?|MUTATIONS?|mutants?|mutations?|CONTROLS?|controls?|FIXTURES?|fixtures?|REJECTS?|rejects?)$')
IMPL_DEFAULT = ('src/**', 'vm/*.wat', 'vm/model/**', 'scripts/run-*.mjs')
RED_WORDING = re.compile(r'gate is red|fails at this commit|not green', re.I)
COORDINATOR_PATHS = ('docs/compiler-campaign/**', 'docs/COMPILER-CAMPAIGN.md', 'scripts/gates/**', 'tools/census/**',
                     'package.json', 'AGENTS.md')


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()[:16]


def _authorized(ctx, path: str, *kinds: str) -> bool:
    for entry in ctx.manifest.authorized():
        if globs.match(entry.get('path', ''), path) and (entry.get('change') in (None, *kinds) or not kinds):
            return True
    return False


# ---- R1 ---------------------------------------------------------------------
def out_of_scope(ctx) -> list[Condition]:
    if not ctx.manifest.declared_owns:
        return []
    appends = ctx.manifest.appends()
    found = []
    for change in ctx.changes():
        path = change.path
        if ctx.manifest.is_owned(path) or path in appends:
            continue
        if globs.match('docs/compiler-campaign/inventory/*.json', path):
            continue                                  # regenerated by the census; a known merge condition
        other = re.match(r'tests/compiler-([^/]+)/', path)
        foreign = bool(other and other.group(1) != ctx.inc) or globs.match_any(COORDINATOR_PATHS, path)
        found.append(Condition(ID, 'out-of-scope-edit', 'major' if foreign else 'minor', {'path': path},
                               value={'status': change.status},
                               expected='changed paths lie inside the manifest\'s owns or appends',
                               observed=f"{change.status} {path} is outside this increment's write scope",
                               fix_hint='Revert it, or record a coordinator authorization (a commit message is not authority).'))
    return found


# ---- R2 ---------------------------------------------------------------------
def _gates_range(source: str) -> tuple[int, int] | None:
    try:
        module = ast.parse(source)
    except SyntaxError:
        return None
    for node in module.body:
        if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == 'GATES' for t in node.targets):
            return node.lineno, node.end_lineno
    return None


def _set_range(source: str) -> tuple[int, int] | None:
    try:
        module = ast.parse(source)
    except SyntaxError:
        return None
    for node in ast.walk(module):
        if isinstance(node, ast.Call) and getattr(node.func, 'attr', '') == 'assertLessEqual' and node.args \
                and isinstance(node.args[0], ast.Set):
            return node.args[0].lineno, node.args[0].end_lineno
    return None


def _outside(base_text: str, head_text: str, base_range, head_range) -> list[str]:
    """Changed lines outside the allowed region (inserts outside head's, deletes/replaces outside base's)."""
    a, b = base_text.split('\n'), head_text.split('\n')
    offending = []
    for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, a, b, autojunk=False).get_opcodes():
        if tag == 'equal':
            continue
        if tag == 'insert':
            inside = head_range and head_range[0] <= j1 + 1 and j2 <= head_range[1]
            if not inside:
                offending += b[j1:j2]
        else:
            inside = base_range and base_range[0] <= i1 + 1 and i2 <= base_range[1]
            if not inside:
                offending += a[i1:i2] + b[j1:j2]
    return [line for line in offending if line.strip()]


def shared_shape(ctx) -> list[Condition]:
    found = []
    for path, shape in ctx.manifest.appends().items():
        if not (ctx.head.has(path) and ctx.base is not None and ctx.base.has(path)) or ctx.head.same(ctx.base, path):
            continue
        base_text, head_text = ctx.base.text(path) or '', ctx.head.text(path) or ''
        severity = 'major' if path.endswith('run.py') else 'minor'
        problems: list[str] = []
        if shape == 'gate-row':
            before = {g.name: g for g in gates_lib.parse_gates(base_text)}
            after = {g.name: g for g in gates_lib.parse_gates(head_text)}
            for name, row in before.items():
                if name not in after:
                    problems.append(f'gate {name} removed')
                elif (after[name].argv, after[name].outputs, after[name].needs) != (row.argv, row.outputs, row.needs):
                    problems.append(f'gate {name} changed')
            if not _authorized(ctx, path, 'counts'):
                problems += [f'line outside the GATES table: {l.strip()[:60]}' for l in
                             _outside(base_text, head_text, _gates_range(base_text), _gates_range(head_text))[:3]]
        elif shape == 'required-name':
            removed = gates_lib.required_names(base_text) - gates_lib.required_names(head_text)
            if removed:
                problems.append(f'required name(s) removed: {sorted(removed)}')
            problems += [f'line outside the required-name set: {l.strip()[:60]}' for l in
                         _outside(base_text, head_text, _set_range(base_text), _set_range(head_text))[:3]]
        elif shape == 'gate-paragraph':
            problems += [f'deleted line: {line.strip()[:60]}' for line in
                         (l for h in diffs.parse(ctx.repo.patch(ctx.base.treeish, ctx.head.treeish, [path], unified=0)).get(path, [])
                          for l in h.removed) if line.strip()][:3]
        else:                                          # census-approval, manifest-group: JSON supersets
            try:
                old, new = json.loads(base_text), json.loads(head_text)
            except ValueError:
                old = new = None
            if old is not None and not _superset(old, new):
                problems.append('an existing entry changed or was removed')
        if problems:
            found.append(Condition(ID, 'shared-file-shape', severity, {'path': path, 'shape': shape},
                                   value={'problems': len(problems)},
                                   expected=f'{path} changes only by its allowed additive shape ({shape})',
                                   observed='; '.join(problems[:3]), evidence={'problems': problems[:8]},
                                   fix_hint='Keep shared files additive; the coordinator resolves anything else at merge.'))
    return found


def _superset(old, new) -> bool:
    if isinstance(old, dict):
        return isinstance(new, dict) and all(k in new and _superset(v, new[k]) for k, v in old.items())
    if isinstance(old, list):
        return isinstance(new, list) and all(any(_superset(o, n) for n in new) for o in old)
    return old == new


# ---- R3 ---------------------------------------------------------------------
def frozen_edits(ctx) -> list[Condition]:
    found = []
    data = ctx.manifest.frozen_data()
    for change in ctx.changes():
        path = change.old_path or change.path
        if change.status == 'A' or not ctx.manifest.is_frozen(path) or globs.match_any(data, path):
            continue                                   # additions are fine; data files get the row check (R6)
        if ctx.manifest.is_authorized(path) or (change.old_path and ctx.manifest.is_authorized(change.path)):
            continue
        assertions = bool(re.search(r'(?:^|/)(?:check[^/]*\.py|trust\.ts|host-check\.py)$', path))
        found.append(Condition(ID, 'frozen-edit', 'blocking' if assertions else 'major', {'path': path},
                               value={'status': change.status},
                               expected='frozen paths are byte-identical to base unless the coordinator authorized the edit',
                               observed=f'{change.status} {path} (frozen)',
                               fix_hint='Revert it. If the edit is wanted, list it in HANDOFF.md as a pending coordinator '
                                        'authorization; a commit message does not authorize.'))
    return found


# ---- R4 ---------------------------------------------------------------------
def _list_sizes(source: str) -> dict:
    """{(name, occurrence): [element labels]} for every assignment of a list/tuple literal named like a control list."""
    try:
        module = ast.parse(source)
    except SyntaxError:
        return {}
    sizes: dict = {}
    seen: dict = {}
    for node in ast.walk(module):
        if isinstance(node, ast.Assign) and isinstance(node.value, (ast.List, ast.Tuple)):
            for target in node.targets:
                name = target.id if isinstance(target, ast.Name) else None
                if name and LIST_NAMES.match(name):
                    labels = []
                    for element in node.value.elts:
                        head = element.elts[0] if isinstance(element, (ast.Tuple, ast.List)) and element.elts else element
                        labels.append(head.value if isinstance(head, ast.Constant) else ast.dump(head)[:40])
                    index = seen.get(name, 0)
                    seen[name] = index + 1
                    sizes[(name, index)] = labels
    return sizes


def _pairs(hunk):
    for removed in hunk.removed:
        best, ratio = None, 0.0
        for added in hunk.added:
            score = difflib.SequenceMatcher(None, removed, added).ratio()
            if score > ratio:
                best, ratio = added, score
        yield removed, best, ratio


def _numbers(line: str) -> list[int]:
    return [int(x.replace('_', '')) for x in re.findall(r'\b\d[\d_]*\b', line)]


def assertion_weakening(ctx) -> list[Condition]:
    if ctx.base is None:
        return []
    found = []
    modified = [c for c in ctx.changes() if c.status in 'MR' and GATE_SCRIPT.match(c.old_path or c.path)]
    for change in modified:
        path = change.path
        if _authorized(ctx, path) or ctx.manifest.is_owned(path):
            continue
        patch = ctx.repo.patch(ctx.base.treeish, ctx.head.treeish, [path], unified=0)
        kinds: dict[str, str] = {}
        for hunk in diffs.parse(patch).get(path, []):
            for removed, added, ratio in _pairs(hunk):
                text = removed.strip()
                if ASSERT_LINE.match(removed) and (added is None or ratio < 0.5 or not ASSERT_LINE.match(added)):
                    if not any(text[:40] in a for a in hunk.added):
                        kinds.setdefault('assertion-removed', text)
                    continue
                if added is None or ratio < 0.6:
                    continue
                m = re.search(r"(\w+)\[(['\"]\w+['\"])\]", removed)
                if m and f'{m[1]}.get({m[2]}' in added:
                    kinds.setdefault('index-to-get', text)
                elif ' == ' in removed and ' == ' not in added and re.search(r' in |startswith\(|endswith\(|>=|<=| > | < ', added):
                    kinds.setdefault('equality-loosened', text)
                elif len(_numbers(removed)) == len(_numbers(added)) and _numbers(removed) != _numbers(added):
                    before, after = _numbers(removed), _numbers(added)
                    widened = (re.search(r'<=?|timeout|budget|limit|max', removed) and sum(after) > sum(before)) or \
                              (re.search(r'>=?|\bmin', removed) and sum(after) < sum(before))
                    if widened and re.search(r'require|assert|raise|if |while ', removed):
                        kinds.setdefault('bound-widened', text)
        old_lists = _list_sizes(ctx.base.text(change.old_path or path) or '')
        new_lists = _list_sizes(ctx.head.text(path) or '')
        for key, labels in old_lists.items():
            if key in new_lists and len(new_lists[key]) < len(labels):
                gone = sorted(set(map(str, labels)) - set(map(str, new_lists[key])))
                kinds.setdefault(f'list-shrunk:{key[0]}', f'{key[0]} lost {gone[:5]}')
        for kind, text in sorted(kinds.items()):
            found.append(Condition(ID, 'assertion-weakened', 'major', {'path': path, 'kind': kind, 'text': _sha(text)},
                                   expected='an existing gate keeps every assertion, bound and control it had',
                                   observed=f'{kind}: {text[:120]}',
                                   fix_hint='Restore it, or list the edit as a pending coordinator authorization.'))
    return found


# ---- R5 ---------------------------------------------------------------------
def coverage_dropped(ctx) -> list[Condition]:
    if ctx.base is None:
        return []
    found = []
    for change in ctx.changes():
        if change.status not in 'MR' or not R.is_receipt(change.path) or not change.path.endswith('.json'):
            continue
        old = R.parse_json(R.read_text(ctx.base, change.old_path or change.path) or '')
        new = R.parse_json(R.read_text(ctx.head, change.path) or '')
        if not isinstance(old, dict) or not isinstance(new, dict):
            continue
        drops = []
        for key in COVERAGE_KEYS:
            if isinstance(old.get(key), list) and isinstance(new.get(key), list) and len(new[key]) < len(old[key]):
                names = lambda rows: {str(r.get('name') or r.get('file') or r.get('id') or json.dumps(r, sort_keys=True)[:40])
                                      if isinstance(r, dict) else str(r) for r in rows}
                drops.append((key, len(old[key]), len(new[key]), sorted(names(old[key]) - names(new[key]))[:5]))
        for key in ('accepted', 'fuzz_accepted', 'accepted_count'):
            if isinstance(old.get(key), int) and isinstance(new.get(key), int) and new[key] < old[key]:
                drops.append((key, old[key], new[key], []))
        for key, before, after, removed in drops:
            found.append(Condition(ID, 'coverage-dropped', 'major', {'path': change.path, 'key': key},
                                   value={'before': before, 'after': after},
                                   expected='a refreshed receipt covers at least what it covered at base',
                                   observed=f'{key}: {before} -> {after}' + (f'; removed {removed}' if removed else ''),
                                   fix_hint='Restore the dropped entries, or record why they went.'))
    return found


# ---- R6 ---------------------------------------------------------------------
def _missing_rows(old, new, pointer='') -> list[str]:
    if isinstance(old, dict):
        if not isinstance(new, dict):
            return [pointer or '/']
        out = []
        for key, value in old.items():
            child = pointer + '/' + str(key).replace('~', '~0').replace('/', '~1')
            out += [child] if key not in new else _missing_rows(value, new[key], child)
        return out
    if isinstance(old, list):
        if not isinstance(new, list):
            return [pointer or '/']
        out = []
        for i, value in enumerate(old):
            if not any(not _missing_rows(value, other) for other in new):
                out.append(f'{pointer}/{i}')
        return out
    return [] if old == new else [pointer or '/']


def frozen_rows(ctx) -> list[Condition]:
    if ctx.base is None:
        return []
    found = []
    patterns = ctx.manifest.frozen_data()
    for change in ctx.changes():
        path = change.path
        if change.status not in 'MR' or not globs.match_any(patterns, change.old_path or path) or not path.endswith('.json'):
            continue
        if ctx.manifest.is_owned(path) and not globs.match_any(patterns, path):
            continue
        try:
            old = json.loads(ctx.base.text(change.old_path or path) or 'null')
            new = json.loads(ctx.head.text(path) or 'null')
        except ValueError:
            continue
        missing = _missing_rows(old, new)
        if not missing:
            continue
        changing = []
        for commit in ctx.commits():
            if commit.is_merge or not any(f.path == path for f in ctx.repo.commit_files(commit.sha)):
                continue
            try:
                before = json.loads((ctx.repo.blob(f'{commit.sha}^:{path}') or b'null').decode('utf-8', 'replace'))
                after = json.loads((ctx.repo.blob(f'{commit.sha}:{path}') or b'null').decode('utf-8', 'replace'))
            except ValueError:
                continue
            if before is not None and _missing_rows(before, after):
                changing.append(commit)                 # this commit, not an additive one, changed a frozen row
        amended = bool(changing) and all(re.search(r'(?m)^amend:', c.body) for c in changing)
        found.append(Condition(ID, 'frozen-row-changed', 'info' if amended else 'major', {'path': path},
                               actor='coordinator' if amended else 'executor', value={'rows': len(missing)},
                               expected='rows of a frozen data file are identical at head (additions are allowed)',
                               observed=f'{len(missing)} base row(s) differ or vanished, e.g. {missing[:3]}'
                                        + (' (amend: note present)' if amended else ''),
                               evidence={'pointers': missing[:8]},
                               fix_hint='Restore the rows, or add an `amend:` line citing the finding or seed observation.'))
    return found


# ---- R7 ---------------------------------------------------------------------
def freeze_order(ctx) -> list[Condition]:
    if ctx.base_commit is None or ctx.head_commit is None:
        return []
    commits = [c for c in ctx.commits() if not c.is_merge]
    if not commits:
        return []
    impl = list(ctx.manifest.get('impl', IMPL_DEFAULT) or IMPL_DEFAULT)
    order = {c.sha: i for i, c in enumerate(commits)}
    touched = {c.sha: ctx.repo.commit_files(c.sha) for c in commits}
    first_impl = next((order[sha] for sha in order if any(globs.match_any(impl, f.path) for f in touched[sha])), None)
    found = []
    added_in: dict[str, str] = {}
    for sha in order:
        for f in touched[sha]:
            if f.status == 'A' and f.path not in added_in and (EXPECTATION_LIKE.search(f.path)
                                                               or globs.match_any(ctx.manifest.get('expectations', []) or [], f.path)):
                added_in[f.path] = sha
    for path, sha in added_in.items():
        if not ctx.head.has(path):
            continue
        if first_impl is not None and order[sha] >= first_impl:
            severity = 'major' if ctx.manifest.prompt_requires_freeze_first() else 'minor'
            found.append(Condition(ID, 'freeze-order', severity, {'path': path}, actor='coordinator',
                                   expected='expectations are committed before the first implementation commit (D7)',
                                   observed=f'{path} was added in {sha[:8]}, not before implementation commit '
                                            f'{commits[first_impl].sha[:8]}',
                                   fix_hint='History is immutable; the ledger records it once by commit.'))
        value = None
        try:
            value = json.loads(ctx.head.text(path) or 'null') if path.endswith('.json') else None
        except ValueError:
            pass
        if isinstance(value, dict):
            frozen_at = value.get('implementation_at_freeze')
            if isinstance(frozen_at, str) and re.fullmatch(r'[0-9a-f]{40}', frozen_at):
                actual = ctx.repo.out('rev-parse', '--verify', '--quiet', f'{sha}^:src', check=False) or None
                if actual and actual != frozen_at:
                    found.append(Condition(ID, 'provenance-mismatch', 'minor', {'path': path, 'field': 'implementation_at_freeze'},
                                           actor='coordinator', expected='implementation_at_freeze equals the src tree before the freeze commit',
                                           observed=f'{frozen_at[:10]} != {actual[:10]}'))
            command = json.dumps((value.get('observed') or {}).get('command')) if isinstance(value.get('observed'), dict) else ''
            if '.local/b/' in command:
                found.append(Condition(ID, 'provenance-mismatch', 'minor', {'path': path, 'field': 'observed.command'},
                                       actor='coordinator', expected='observations call the pinned seed',
                                       observed='observed.command runs a local build (.local/b/*), not the pinned seed'))
    return found


# ---- R8 ---------------------------------------------------------------------
def generators(ctx) -> tuple[list[Condition], str]:
    declared = ctx.manifest.get('generators', []) or []
    if not declared:
        return [], 'no generators declared in the manifest'
    import subprocess
    found = []
    export = ctx.export(ctx.head)
    scratch = ctx.scratch / 'generators'
    scratch.mkdir(parents=True, exist_ok=True)
    for generator in declared:
        cmd = generator.get('cmd') or []
        outputs = generator.get('outputs') or []
        code, _out, err = ctx.run(cmd, cwd=export, timeout=10)
        if code != 0:
            found.append(Condition(ID, 'generator-not-reproducible', 'minor', {'path': ' '.join(cmd)}, actor='executor',
                                   observed=f'generator exited {code}: {err.decode(errors="replace")[:120]}',
                                   expected='a touched generator reruns and reproduces its tracked output'))
            continue
        for output in outputs:
            produced = (export / output).read_bytes() if (export / output).exists() else None
            tracked = ctx.head.read(output)
            if produced != tracked:
                found.append(Condition(ID, 'generator-not-reproducible', 'minor', {'path': output}, actor='executor',
                                       expected='rerunning the generator reproduces the tracked file',
                                       observed=f'{output} differs after rerunning {" ".join(cmd)}',
                                       fix_hint='Regenerate and commit, or fix the generator.'))
    return found, ''


# ---- R9 ---------------------------------------------------------------------
def normalized_comparison(ctx) -> list[Condition]:
    found = []
    plan, expected = 'vm/golden/plan.json', 'vm/golden/expectations.json'
    if ctx.head.has(plan) and ctx.head.has(expected):
        try:
            p, e = json.loads(ctx.head.text(plan)), json.loads(ctx.head.text(expected))
        except ValueError:
            p = e = None
        rows = lambda doc: {r.get('name'): r.get('seed_stdout') for r in (doc if isinstance(doc, list) else doc.get('goldens', doc.get('rows', [])))
                            if isinstance(r, dict)} if doc is not None else {}
        a, b = rows(p), rows(e)
        differing = sorted(n for n in set(a) & set(b) if a[n] != b[n])
        if differing:
            found.append(Condition(ID, 'normalized-comparison', 'minor', {'path': plan}, value={'rows': len(differing)},
                                   expected='seed_stdout is byte-identical in the plan and the expectations',
                                   observed=f'{len(differing)} row(s) differ, e.g. {differing[:3]}'))
    pattern = re.compile(r"seed\w*[^\n]*\.(?:replace|strip|lstrip|rstrip)\(|\.(?:replace|strip)\([^\n]*\)[^\n]*seed_stdout")
    for change in ctx.changes():
        if change.status in 'AMR' and GATE_SCRIPT.match(change.path):
            patch = ctx.repo.patch(ctx.base.treeish, ctx.head.treeish, [change.path], unified=0)
            for hunk in diffs.parse(patch).get(change.path, []):
                for line in hunk.added:
                    if pattern.search(line):
                        found.append(Condition(ID, 'normalized-comparison', 'minor', {'path': change.path, 'text': _sha(line)},
                                               expected='seed values are compared byte for byte',
                                               observed=f'seed value compared through a normalization: {line.strip()[:100]}'))
    return found


# ---- R10 --------------------------------------------------------------------
def history(ctx) -> list[Condition]:
    found = []
    family = {'claude': 'claude', 'codex': 'codex|gpt'}.get(str(ctx.manifest.executor()).lower(), str(ctx.manifest.executor()).lower())
    merge_as_unit = bool(ctx.manifest.get('merge_as_unit', False))
    readme = ctx.head.text(f'tests/compiler-{ctx.inc}/README.md') if ctx.inc else None
    if readme and re.search(r'merge as a unit', readme, re.I):
        merge_as_unit = True
    for commit in ctx.commits():
        if commit.is_merge:
            continue
        trailers = re.findall(r'(?im)^co-authored-by:\s*(.+)$', commit.body)
        if not any(re.search(family, t, re.I) for t in trailers):
            found.append(Condition(ID, 'commit-trailer', 'minor', {'commit': commit.sha}, actor='coordinator',
                                   expected=f'every non-merge commit carries a Co-Authored-By trailer naming the executor ({ctx.manifest.executor()})',
                                   observed=f'{commit.sha[:8]} {commit.subject[:60]!r}: '
                                            + ('no Co-Authored-By trailer' if not trailers else f'trailer names {trailers[0][:40]!r}')))
        if RED_WORDING.search(commit.body) and not merge_as_unit:
            found.append(Condition(ID, 'red-commit-wording', 'info', {'commit': commit.sha}, actor='coordinator',
                                   expected='intermediate red commits are declared as a unit in the README',
                                   observed=f'{commit.sha[:8]} says the gate is red at this commit'))
        files = ctx.repo.commit_files(commit.sha)
        if any(f.path == 'tools/census/approved.json' for f in files) and 'census:approve' not in commit.body:
            found.append(Condition(ID, 'census-approval-summary', 'minor', {'commit': commit.sha}, actor='coordinator',
                                   expected='a commit that changes approved.json carries the census:approve summary',
                                   observed=f'{commit.sha[:8]} edits approved.json without the summary'))
        other_gate = [f.path for f in files if GATE_SCRIPT.match(f.path) and not ctx.manifest.is_owned(f.path)
                      and f.status in 'MR' and not f.path.startswith('scripts/gates/')]
        if other_gate and any(f.path.startswith('src/') and f.path.endswith('.bend') for f in files):
            found.append(Condition(ID, 'mixed-gate-commit', 'info', {'commit': commit.sha}, actor='coordinator',
                                   expected='a commit does not change another gate\'s check script together with src/*.bend',
                                   observed=f'{commit.sha[:8]} touches {other_gate[0]} and src/*.bend'))
    return found


# ---- R11 --------------------------------------------------------------------
def red_tip(ctx) -> tuple[list[Condition], str]:
    export = ctx.export(ctx.head)
    if not (export / 'tools/census/census.mjs').exists():
        return [], 'no tools/census in this tree'
    found = []
    code, out, err = ctx.run(['node', 'tools/census/census.mjs', '--check'], cwd=export, timeout=60)
    if code is None:
        return [], 'census --check timed out or node is missing'
    if code != 0:
        found.append(Condition(ID, 'red-tip', 'major', {'command': 'census --check'}, expected='census --check passes at head',
                               observed=(err or out).decode(errors='replace').strip().splitlines()[-1][:160] if (err or out) else f'exit {code}',
                               fix_hint='Run `npm run census` and review the approval policy.'))
    if (export / 'tools/census/tests').is_dir():
        tests = sorted(p.name for p in (export / 'tools/census/tests').glob('*.test.mjs'))
        code, out, err = ctx.run(['node', '--test', *[f'tools/census/tests/{t}' for t in tests]], cwd=export, timeout=120)
        if code not in (0, None):
            failed = re.findall(r'(?m)^not ok \d+ - (.+)$', out.decode(errors='replace'))
            found.append(Condition(ID, 'red-tip', 'major', {'command': 'census:test'}, value={'failed': len(failed)},
                                   expected='npm run census:test passes at head',
                                   observed=f'{len(failed)} failing test(s): {failed[:2]}',
                                   fix_hint='census:test is not a registered gate, so nothing else catches this.'))
        elif code is None:
            return found, 'census:test timed out'
    return found, ''


def run(ctx) -> CheckResult:
    result = CheckResult()
    if ctx.base is None:
        return CheckResult(outcome='not-applicable', reason='no base to compare against')
    rules = [('out-of-scope-edit', out_of_scope), ('shared-file-shape', shared_shape), ('frozen-edit', frozen_edits),
             ('assertion-weakened', assertion_weakening), ('coverage-dropped', coverage_dropped),
             ('frozen-row-changed', frozen_rows), ('freeze-order', freeze_order),
             ('normalized-comparison', normalized_comparison), ('history', history)]
    if not ctx.manifest.declared_owns:
        result.rules_unavailable['out-of-scope-edit'] = 'no `owns` declared in the increment manifest'
        rules = [r for r in rules if r[0] != 'out-of-scope-edit']
    if ctx.identity and not ctx.commits():
        return CheckResult(outcome='pass', reason='identity: nothing changed since base', rules_run=[])
    for name, fn in rules:
        result.conditions += fn(ctx)
        result.rules_run.append(name)
    found, reason = generators(ctx)
    result.conditions += found
    if reason:
        result.rules_unavailable['generator-not-reproducible'] = reason
    else:
        result.rules_run.append('generator-not-reproducible')
    if ctx.options.get('census', True) and not ctx.identity and any(
            p.startswith(('src/', 'tools/census/', 'docs/compiler-campaign/inventory/')) for p in ctx.changed_paths() + ctx.deleted_paths()):
        found, reason = red_tip(ctx)
        result.conditions += found
        if reason:
            result.rules_unavailable['red-tip'] = reason
        else:
            result.rules_run.append('red-tip')
    return result


CHECK = Check(ID, 'frozen-and-owned', 'frozen and owned artifacts and the history since the base', run, budget=15)
