type Flag is Data:
  Off{}
  On{}
type Chain is Type:
  End{}
  Link{value: Flag, next: Chain}
def main() -> Chain:
  Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},Link{On{},End{}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}
