#!/usr/bin/env python3
"""Freeze or verify the self-hosting joint suite against the pinned seed, on two lanes.

    python3 tests/compiler-selfhost/regen.py            # verify (default; `verify` is accepted)
    python3 tests/compiler-selfhost/regen.py --write    # rewrite the observations section

Every seed observation is taken on both of the seed's oracle lanes:

- `interpreter`: `bun main.ts <file>`, the reference interpreter;
- `native`: `bun main.ts <file> -o <bin>` (clang), then `<bin>`, the lane C1 is built on.

A lane disagreement is never averaged away. It passes only when a hand-reviewed
`lane_decisions` entry names it (DEC-7); an unreviewed one fails.

Check mode recomputes every observation and the generated scale fixtures, then
compares them with `expectations.json` exactly. `--write` rewrites only the
`observations` section and the generated fixtures. The hand-reviewed sections
(`needs`, `cases`, `lane_decisions`) are never changed here; they are validated
against the seed's classification. Nothing here runs or reads Knot.

Commands run from the repository root with relative paths, so recorded argv and
output are identical in every checkout. Builds, wrappers and sandboxes live in
the ignored `.local/compiler-selfhost/seed/`, which is cleared first.
"""
from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor
import difflib
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SUITE = 'tests/compiler-selfhost'
FIXTURES = f'{SUITE}/fixtures'
EXPECTATIONS = HERE / 'expectations.json'
TOOLCHAIN = '.toolchain/bend-2.0.29-574b6d3/bend2/'
SEED = TOOLCHAIN + 'main.ts'
SEED_FILES = [TOOLCHAIN + name for name in (
    'main.ts', 'bend.ts', 'comp.ts', 'base.bend',
    *(f'effs/{e}.{x}' for e in ('args', 'print', 'print_err', 'file_open', 'file_read', 'file_close')
      for x in ('js', 'c')))]
PACKAGES = {'0xc409b77d3230ca33374caf6b0993f0cb/bytes.bend':
            'Hash-pinned ByteOutput package in the seed store (BEND_LIB, default ~/.bend/lib)'}
WORK = '.local/compiler-selfhost/seed'
SCALE = os.environ.get('KNOT_GATE_TIMEOUT_SCALE', '1')
TIMEOUT = 180 * float(SCALE)  # harness hang guard only; a timeout is never an observation
JOBS = int(os.environ.get('KNOT_SELFHOST_JOBS', '6'))
LEAKS = ('/Users/', '/home/', '/private/', '/tmp/', '.claude/worktrees', str(ROOT))
REQUIRES = {'agree', 'reject', 'unsupported'}
KINDS = {'value', 'io'}
STREAM_LIMIT = 4096


class Mismatch(Exception):
    pass


def require(condition, detail):
    if not condition:
        raise Mismatch(detail)


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def env():
    return {**os.environ, 'BEND_NO_TELEMETRY': '1'}


def execute(argv, cwd=ROOT):
    try:
        p = subprocess.run([str(a) for a in argv], cwd=cwd, env=env(), stdin=subprocess.DEVNULL,
                           capture_output=True, timeout=TIMEOUT)
    except subprocess.TimeoutExpired:
        raise Mismatch(('a seed timeout is exhaustion of the harness, not an observation', argv))
    out = {'argv': [str(a) for a in argv], 'exit': p.returncode,
           'stdout': p.stdout.decode(), 'stderr': p.stderr.decode()}
    return out


HOST_TOOLCHAIN = 'bend needs clang'


def build(argv):
    """A native build. The seed's clang probe can fail to spawn under host load;
    that is a host failure, never an observation: retry it, then abort."""
    for _ in range(3):
        built = execute(argv)
        if not (built['exit'] != 0 and HOST_TOOLCHAIN in built['stderr'] and 'found no clang' in built['stderr']):
            return built
    raise Mismatch(('host failure: the seed found no clang three times', built))


# ---------------------------------------------------------------- scale bundle

def scale_bundle() -> dict[str, str]:
    """Twenty modules plus an entry and Base: 782 functions, a 720-link chain.

    Module k defines links `s{k}_0 .. s{k}_35` and conversions to and from
    module k-1's Flag; `s{k}_0` calls module k-1's last link, so the entry
    reaches every link through one call. A link inverts its flag where
    (k + i) % 3 == 0, so the result depends on the whole chain.
    """
    files = {}
    width, depth = 20, 36
    for k in range(width):
        lines = ['# Generated by regen.py (scale-bundle); do not edit.', 'import Base']
        if k:
            lines.append(f'import ./m{k - 1:02}.bend as P')
        lines += ['', 'type Flag is Data:', '  Off{}', '  On{}', '']
        lines += ['def flip(x: Flag) -> Flag:', '  match x:', '    case Off{}: On{}', '    case On{}: Off{}', '']
        if k:
            lines += ['def lift(x: P.Flag) -> Flag:', '  match x:', '    case P.Off{}: Off{}',
                      '    case P.On{}: On{}', '', 'def lower(x: Flag) -> P.Flag:', '  match x:',
                      '    case Off{}: P.Off{}', '    case On{}: P.On{}', '']
        for i in range(depth):
            if i == 0:
                body = f'lift(P.s{k - 1}_{depth - 1}(lower(x)))' if k else 'x'
            else:
                body = f'flip(s{k}_{i - 1}(x))' if (k + i) % 3 == 0 else f's{k}_{i - 1}(x)'
            lines += [f'def s{k}_{i}(x: Flag) -> Flag:', f'  {body}', '']
        files[f'scale-bundle/m{k:02}.bend'] = '\n'.join(lines).rstrip('\n') + '\n'
    last = width - 1
    files['scale-bundle/main.bend'] = '\n'.join([
        '# Generated by regen.py (scale-bundle); do not edit.',
        '# 782 functions across 20 modules plus Base: one 720-link call chain.',
        'import Base', f'import ./m{last:02}.bend as M', '',
        'type Answer is Type:', '  No{}', '  Yes{}', '',
        'type Seed is Type:', '  Low{}', '  High{}', '',
        'def answer(x: M.Flag) -> Answer:',
        '  match x:', '    case M.Off{}: No{}', '    case M.On{}: Yes{}', '',
        'def start(s: Seed) -> M.Flag:', '  match s:', '    case Low{}: M.Off{}', '    case High{}: M.On{}', '',
        'def through(s: Seed) -> Answer:', f'  answer(M.s{last}_{depth - 1}(start(s)))', '',
        'def main() -> Answer:', '  through(High{})', ''])
    return files


def scale_catalog() -> dict[str, str]:
    """One Base-free book of 723 functions: the catalog limit without modules."""
    count = 720
    lines = ['# Generated by regen.py (scale-catalog); do not edit.',
             '# 723 functions in one book, past the 256-function catalog limit.', '',
             'type Flag is Type:', '  Off{}', '  On{}', '',
             'def flip(x: Flag) -> Flag:', '  match x:', '    case Off{}: On{}', '    case On{}: Off{}', '']
    for i in range(count):
        body = 'x' if i == 0 else (f'flip(c{i - 1}(x))' if i % 7 == 0 else f'c{i - 1}(x)')
        lines += [f'def c{i}(x: Flag) -> Flag:', f'  {body}', '']
    lines += ['def through(x: Flag) -> Flag:', f'  c{count - 1}(x)', '',
              'def main() -> Flag:', '  through(On{})', '']
    return {'scale-catalog/main.bend': '\n'.join(lines)}


GENERATED = {**scale_bundle(), **scale_catalog()}


# ---------------------------------------------------------------- syntax readings

def enums(source: str) -> dict[str, list[str]]:
    """Nullary enum declarations in constructor order: a syntactic reading only."""
    found, lines = {}, source.split('\n')
    for i, line in enumerate(lines):
        header = re.fullmatch(r'type (\w+) is (?:Data|Type):', line)
        if not header:
            continue
        body = []
        for later in lines[i + 1:]:
            if not later.startswith('  '):
                break
            body.append(later)
        arms = [re.fullmatch(r'  (\w+)\{\}', l) for l in body]
        if body and all(arms):
            found[header.group(1)] = [m.group(1) for m in arms]
    return found


def result_type(source: str, entry: str) -> str | None:
    match = re.search(rf'^def {re.escape(entry)}\((.*?)\) -> (\w+):$', source, re.M | re.S)
    return match.group(2) if match else None


# ---------------------------------------------------------------- observation

def wrapper_text(entry_rel: str, wrapper: str, result: str, entry: str, args) -> str:
    imported = os.path.relpath(ROOT / entry_rel, (ROOT / wrapper).parent)
    call = ', '.join(f'F.{a}{{}}' for a in args)
    return (f'import Base\nimport {imported} as F\n\n'
            f'def main() -> F.{result}:\n  F.{entry}({call})\n')


def prefix(entry_rel: str, wrapper: str) -> str:
    return os.path.relpath(ROOT / entry_rel, (ROOT / wrapper).parent).removesuffix('.bend') + '.'


def lanes_for_call(case, entry, args, result, build_dir):
    """One call on both lanes through one wrapper; no lane interpretation yet."""
    name = case['name']
    label = entry['name'] + ('--' + '-'.join(args) if args else '')
    wrapper = f'{WORK}/wrappers/{name}/{label}.bend'
    text = wrapper_text(case['files'][0], wrapper, result, entry['name'], args)
    (ROOT / wrapper).parent.mkdir(parents=True, exist_ok=True)
    (ROOT / wrapper).write_text(text)
    binary = f'{build_dir}/{name}--{label}'
    interpreter = execute(['bun', SEED, wrapper])
    built = build(['bun', SEED, wrapper, '-o', binary])
    native = execute([f'./{binary}']) if built['exit'] == 0 else None
    return wrapper, interpreter, built, native


def constructor(stdout: str, pre: str, constructors) -> str | None:
    match = re.fullmatch(re.escape(pre) + r'(\w+)\{\}\n', stdout)
    return match.group(1) if match and match.group(1) in constructors else None


def observe_value(case, types):
    calls, jobs = [], []
    build_dir = f'{WORK}/bin'
    (ROOT / build_dir).mkdir(parents=True, exist_ok=True)
    source = (ROOT / case['files'][0]).read_text()
    for entry in case['entries']:
        result = result_type(source, entry['name'])
        require(result == entry['result'], (case['name'], entry['name'], 'declared result differs', result))
        require(result in types, (case['name'], 'an observed result is a nullary enum of the entry', result))
        for p in entry['params']:
            require(p in types, (case['name'], 'observed parameters are nullary enums of the entry', p))
        for args in entry['calls']:
            require(len(args) == len(entry['params']) and
                    all(a in types[p] for a, p in zip(args, entry['params'])),
                    (case['name'], entry['name'], 'call arguments are constructors of the parameters', args))
            jobs.append((entry, args, result))
    with ThreadPoolExecutor(JOBS) as pool:
        raw = list(pool.map(lambda j: lanes_for_call(case, j[0], j[1], j[2], build_dir), jobs))
    for (entry, args, result), (wrapper, interpreter, built, native) in zip(jobs, raw):
        pre = prefix(case['files'][0], wrapper)
        seen = {'interpreter': constructor(interpreter['stdout'], pre, types[result])
                if interpreter['exit'] == 0 and interpreter['stderr'] == '' else None,
                'native': constructor(native['stdout'], pre, types[result])
                if native and native['exit'] == 0 and native['stderr'] == '' else None}
        call = {'entry': entry['name'], 'arguments': list(args),
                'ordinals': [types[p].index(a) for p, a in zip(entry['params'], args)],
                'wrapper': wrapper,
                'interpreter': outcome(interpreter),
                'native': {'build': outcome(built), 'run': outcome(native)}}
        if seen['interpreter'] is not None and seen['interpreter'] == seen['native']:
            call['lanes'] = 'agree'
            ctor = seen['interpreter']
        else:
            call['lanes'] = 'disagree'
            decision = lane_decision(case['name'], entry['name'], args)
            require(decision is not None, (case['name'], entry['name'], args,
                                           'unreviewed lane disagreement (DEC-7)', interpreter, built, native))
            ctor = seen.get(decision['oracle'])
            call['decision'] = decision['id']
        call['result'] = None if ctor is None else {
            'type': result, 'constructor': ctor, 'tag': types[result].index(ctor)}
        calls.append(call)
    return calls


def strip(record):
    return None if record is None else {k: record[k] for k in ('argv', 'exit', 'stdout', 'stderr')}


def outcome(record):
    """A call's lane record; its argv follows from the wrapper path."""
    return None if record is None else {k: record[k] for k in ('exit', 'stdout', 'stderr')}


DECISIONS: list[dict] = []


def lane_decision(case, entry, args):
    for d in DECISIONS:
        if d['case'] == case and d.get('entry') == entry and d.get('arguments') == list(args):
            return d
    return None


def sandbox(path: str) -> Path:
    box = ROOT / path
    require(box.resolve().is_relative_to((ROOT / WORK).resolve()), ('sandbox escapes the work dir', path))
    if box.exists():
        shutil.rmtree(box)
    box.mkdir(parents=True)
    return box


def snapshot(box: Path, seeded: dict):
    files = []
    for path in sorted(box.rglob('*')):
        rel = path.relative_to(box).as_posix()
        if path.is_dir():
            files.append({'path': rel, 'type': 'directory'})
            continue
        data = path.read_bytes()
        entry = {'path': rel, 'type': 'file', 'bytes': len(data), 'sha256': digest(data)}
        if len(data) <= STREAM_LIMIT and data.isascii():
            entry['text'] = data.decode()
        if rel in seeded:
            entry['seeded_from'] = seeded[rel]
        files.append(entry)
    return files


def observe_io(case):
    """Whole-program runs: fresh sandbox per lane and run, seeded with tracked inputs."""
    entry = case['files'][0]
    binary = f'{WORK}/bin/{case["name"]}'
    (ROOT / binary).parent.mkdir(parents=True, exist_ok=True)
    built = build(['bun', SEED, entry, '-o', binary])
    runs = []
    for spec in case['runs']:
        record = {'name': spec['name'], 'argv': spec['argv'], 'native_build': strip(built)}
        for lane in ('interpreter', 'native'):
            box = sandbox(f'{WORK}/runs/{case["name"]}/{spec["name"]}/{lane}')
            for dest, source in spec.get('inputs', {}).items():
                target = box / dest
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(ROOT / FIXTURES / case['name'] / source, target)
            up = os.path.relpath(ROOT, box)
            if lane == 'interpreter':
                argv = ['bun', f'{up}/{SEED}', f'{up}/{entry}', '--', *spec['argv']]
            else:
                require(built['exit'] == 0, (case['name'], 'native build failed', built))
                argv = [f'{up}/{binary}', *spec['argv']]
            done = execute(argv, cwd=box)
            record[lane] = {**strip(done), 'files': snapshot(box, spec.get('inputs', {}))}
        same = all(record['interpreter'][k] == record['native'][k] for k in ('exit', 'stdout', 'stderr', 'files'))
        record['lanes'] = 'agree' if same else 'disagree'
        if not same:
            decision = lane_decision(case['name'], None, [spec['name']])
            require(decision is not None, (case['name'], spec['name'], 'unreviewed lane disagreement (DEC-7)',
                                           record['interpreter'], record['native']))
            record['decision'] = decision['id']
        for key, want in spec.get('reviewed', {}).items():
            require(record['interpreter'][key] == want,
                    (case['name'], spec['name'], 'the seed disagrees with a reviewed literal', key, want))
        runs.append(record)
    return runs


def observe_rejection(case):
    """A seed-rejected twin: direct interpreter rejection, and the native build of a
    wrapper that imports it, which is how every native observation is taken."""
    entry = case['files'][0]
    source = (ROOT / entry).read_text()
    result = result_type(source, 'main')
    wrapper = f'{WORK}/wrappers/{case["name"]}/main.bend'
    (ROOT / wrapper).parent.mkdir(parents=True, exist_ok=True)
    (ROOT / wrapper).write_text(wrapper_text(entry, wrapper, result or 'Unit', 'main', []))
    binary = f'{WORK}/bin/{case["name"]}'
    (ROOT / binary).parent.mkdir(parents=True, exist_ok=True)
    direct = execute(['bun', SEED, entry])
    native = build(['bun', SEED, wrapper, '-o', binary])
    require(direct['exit'] == 1 and direct['stdout'] == '' and direct['stderr'].startswith('Error:\n'),
            (case['name'], 'the interpreter must reject', direct))
    require(native['exit'] != 0 and not (ROOT / binary).exists(),
            (case['name'], 'the native lane must reject and build nothing', native))
    # The wrapper sees the twin as a module, so its names carry the import path;
    # the direct run names the entry's own declarations bare and its modules by file.
    directory = os.path.relpath((ROOT / entry).parent, (ROOT / wrapper).parent) + '/'
    unqualified = native['stderr'].replace(prefix(entry, wrapper), '').replace(directory, '')
    for reason in case['seed_reason']:
        require(reason in direct['stderr'] and reason in unqualified,
                (case['name'], 'a lane rejected for another reason', reason, direct, native))
    return {'interpreter': strip(direct), 'at': caret(direct['stderr']),
            'native': {'wrapper': wrapper, 'build': strip(native),
                       'same_report': unqualified == direct['stderr']}}


def caret(stderr: str) -> str | None:
    """The seed's source location as `line:column` (1-based line, 0-based column)."""
    lines = stderr.split('\n')
    for i, line in enumerate(lines[:-1]):
        marked = re.match(r'^\s*(\d+)>\| ', line)
        pointer = re.match(r'^(\s*\| )( *)\^', lines[i + 1])
        if marked and pointer and len(pointer.group(1)) == marked.end():
            return f'{marked.group(1)}:{len(pointer.group(2))}'
    return None


def observe_case(case, needs):
    name = case['name']
    sources = {}
    for rel in case['files']:
        data = (ROOT / rel).read_bytes()
        require(data.isascii() and b'\t' not in data and b'\r' not in data,
                (name, rel, 'fixtures are ASCII with LF line endings and no tabs'))
        sources[rel] = digest(data)
    for rel in case.get('inputs', []):
        sources[rel] = digest((ROOT / rel).read_bytes())
    entry = case['files'][0]
    check = execute(['bun', SEED, entry, '--check-only'])
    item = {'case': name, 'sources': sources, 'check_only': strip(check)}
    types = enums((ROOT / entry).read_text())
    if case['knot']['require'] == 'reject':
        require(check['exit'] == 1 and check['stdout'] == '' and check['stderr'].startswith('Error:\n'),
                (name, 'the seed must reject', check))
        item['rejection'] = observe_rejection(case)
        require(item['rejection']['interpreter']['stderr'] == check['stderr'],
                (name, 'check-only and run report the same rejection'))
        if 'at' in case['knot']:
            located = caret(check['stderr'])
            require(located == case['knot']['at'],
                    (name, 'a pinned position is where the seed points', located, case['knot']['at']))
        return item
    require(check['exit'] == 0 and check['stdout'] == 'All terms check.\n' and check['stderr'] == '',
            (name, 'the seed must check', check))
    if case['kind'] == 'io':
        item['runs'] = observe_io(case)
        return item
    direct = execute(['bun', SEED, entry])
    require(direct['exit'] == 0 and direct['stderr'] == '', (name, 'the interpreter must run main', direct))
    item['run'] = strip(direct)
    item['enums'] = types
    item['calls'] = observe_value(case, types)
    return item


# ---------------------------------------------------------------- review validation

def validate(document):
    """The hand-reviewed sections are well formed and consistent (D4, D7)."""
    needs, cases = document['needs'], document['cases']
    for key, need in needs.items():
        require(set(need) == {'owner', 'available', 'meaning'} and isinstance(need['available'], bool),
                ('malformed need', key, need))
    names = [c['name'] for c in cases]
    require(len(names) == len(set(names)), 'duplicate case names')
    by = {c['name']: c for c in cases}
    listed = set()
    for case in cases:
        name, knot = case['name'], case['knot']
        require(re.fullmatch(r'[a-z0-9]+(-[a-z0-9]+)*', name), (name, 'case names are kebab-case'))
        require(case['kind'] in KINDS, (name, 'unknown kind'))
        require(case['owner'] and case['shape'] and case['requirements'], (name, 'owner, shape, requirements'))
        require(all(re.fullmatch(r'(SF|SCALE|BS|INT)-\d\d', r) for r in case['requirements']), (name, 'ids'))
        require(all(n in needs for n in case['needs']), (name, 'unknown need', case['needs']))
        require(case['files'] and case['files'][0] == f'{FIXTURES}/{name}/main.bend',
                (name, 'the entry is fixtures/<name>/main.bend'))
        require(all(f.startswith(f'{FIXTURES}/{name}/') for f in case['files'] + case.get('inputs', [])),
                (name, 'a case owns only its own directory'))
        listed.update(case['files'] + case.get('inputs', []))
        require(knot['require'] in REQUIRES and knot.get('justification'), (name, 'requirement', knot))
        if knot['require'] == 'agree':
            require(set(knot) == {'require', 'justification'} | ({'budget'} if case['kind'] == 'value' else set()),
                    (name, 'agreement is fixed by the seed, not by a literal', knot))
            require('seed_reason' not in case and 'twin_of' not in case, (name, 'an agree case is seed-accepted'))
        else:
            require(re.fullmatch(r'(Invalid|Unsupported)\t[a-z]+\t[a-z-]+\t', knot['diagnostic']), (name, knot))
            require({'Invalid': 2, 'Unsupported': 3}[knot['diagnostic'].split('\t')[0]] == knot['exit'], (name, knot))
            if 'at' in knot:
                require(re.fullmatch(r'\d+:\d+', knot['at']), (name, 'at is line:column', knot))
        if knot['require'] == 'unsupported':
            require(knot['exit'] == 3 and 'seed_reason' not in case, (name, 'Unsupported of a seed-valid form'))
        if knot['require'] == 'reject':
            require(isinstance(case.get('seed_reason'), list) and case['seed_reason'], (name, 'seed reason'))
            twin = by.get(case.get('twin_of'))
            require(twin is not None and twin.get('twin') == name, (name, 'a rejection is the twin of a positive'))
        if 'twin' in case:
            require(by.get(case['twin'], {}).get('twin_of') == name, (name, 'twin link is mutual'))
        if case['kind'] == 'value' and knot['require'] != 'reject':
            require(case['entries'] and any(e['name'] == 'main' for e in case['entries']), (name, 'main is an entry'))
        if case['kind'] == 'io' and knot['require'] != 'reject':
            require(case['runs'], (name, 'an io case plans runs'))
    on_disk = {p.relative_to(ROOT).as_posix() for p in (HERE / 'fixtures').rglob('*') if p.is_file()}
    require(on_disk == listed, ('fixture files and cases differ', sorted(on_disk ^ listed)))
    for d in document['lane_decisions']:
        require(set(d) >= {'id', 'case', 'arguments', 'oracle', 'decision'} and d['case'] in by, ('decision', d))


def discriminating(document, observations):
    """An accepted value case's calls reach at least two results, so a constant cannot pass."""
    by = {o['case']: o for o in observations['fixtures']}
    for case in document['cases']:
        if case['kind'] == 'value' and case['knot']['require'] == 'agree':
            results = {json.dumps(c['result']) for c in by[case['name']]['calls']}
            require(len(results) >= 2, (case['name'], 'calls reach one result only', results))


def observe_all(document):
    global DECISIONS
    DECISIONS = document['lane_decisions']
    contract = json.loads((ROOT / 'src/CONTRACT.json').read_text())['seed']
    require(document['seed'] == {'version': contract['version'], 'revision': contract['commit'], 'entry': SEED},
            ('seed identity differs from src/CONTRACT.json', document['seed']))
    version = execute(['bun', SEED, 'version'])
    require(version['stdout'] == f"bend {contract['version']}\n", ('unexpected seed version', version))
    validate(document)
    for rel, text in GENERATED.items():
        path = ROOT / FIXTURES / rel
        require(path.exists() and path.read_text() == text, ('generated fixture differs from regen.py', rel))
    if (ROOT / WORK).exists():
        shutil.rmtree(ROOT / WORK)
    observations = {
        'seed_files': {f: digest((ROOT / f).read_bytes()) for f in SEED_FILES},
        'packages': {p: digest(package_path(p).read_bytes()) for p in PACKAGES},
        'fixtures': [observe_case(c, document['needs']) for c in document['cases']]}
    discriminating(document, observations)
    text = json.dumps(observations)
    leaked = [leak for leak in LEAKS if leak in text]
    require(not leaked, ('checkout-specific paths in observations', leaked))
    return observations


def package_path(rel: str) -> Path:
    store = Path(os.environ.get('BEND_LIB', Path.home() / '.bend/lib'))
    return store / rel


def summary(document, observations):
    fixtures = observations['fixtures']
    calls = sum(len(o.get('calls', [])) for o in fixtures)
    runs = sum(len(o.get('runs', [])) for o in fixtures)
    rejected = sum('rejection' in o for o in fixtures)
    disagree = sum(c.get('lanes') == 'disagree' for o in fixtures for c in o.get('calls', []) + o.get('runs', []))
    return (f'{len(fixtures)} cases ({len(fixtures) - rejected} seed-valid, {rejected} seed-rejected), '
            f'{calls} calls and {runs} io runs on 2 lanes, {disagree} reviewed lane disagreements')


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument('mode', nargs='?', default='verify', choices=['verify'])
    parser.add_argument('--write', action='store_true', help='rewrite observations and generated fixtures')
    args = parser.parse_args(argv)
    document = json.loads(EXPECTATIONS.read_text())
    if args.write:
        for rel, text in GENERATED.items():
            path = ROOT / FIXTURES / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    try:
        observations = observe_all(document)
    except Mismatch as e:
        print('regen: FAIL', e, file=sys.stderr)
        return 1
    line = summary(document, observations)
    if args.write:
        document['observations'] = observations
        EXPECTATIONS.write_text(json.dumps(document, indent=2) + '\n')
        print(f'regen: wrote {line}')
        return 0
    stored = document.get('observations')
    if stored != observations:
        before = json.dumps(stored, indent=2).splitlines()
        after = json.dumps(observations, indent=2).splitlines()
        sys.stdout.writelines(l + '\n' for l in difflib.unified_diff(
            before, after, 'expectations.json', 'seed', lineterm='', n=2))
        print('regen: FAIL seed observations differ from expectations.json', file=sys.stderr)
        return 1
    print(f'regen: PASS {line}, identical to expectations.json')
    return 0


if __name__ == '__main__':
    sys.exit(main())
