type Flag is Data:
  Off{}
  On{}
type N is Data:
  Z{}
  S{pred: N}
def f(n: N) -> Flag:
  match n:
    case Z{}: On{}
    case S{p1}:
      match p1:
        case Z{}: On{}
        case S{p2}:
          match p2:
            case Z{}: On{}
            case S{p3}:
              match p3:
                case Z{}: On{}
                case S{p4}:
                  match p4:
                    case Z{}: On{}
                    case S{p5}:
                      match p5:
                        case Z{}: On{}
                        case S{p6}:
                          match p6:
                            case Z{}: On{}
                            case S{p7}:
                              match p7:
                                case Z{}: On{}
                                case S{p8}:
                                  match p8:
                                    case Z{}: On{}
                                    case S{p9}:
                                      match p9:
                                        case Z{}: On{}
                                        case S{p10}:
                                          match p10:
                                            case Z{}: On{}
                                            case S{p11}:
                                              match p11:
                                                case Z{}: On{}
                                                case S{p12}:
                                                  match p12:
                                                    case Z{}: On{}
                                                    case S{p13}:
                                                      match p13:
                                                        case Z{}: On{}
                                                        case S{p14}:
                                                          match p14:
                                                            case Z{}: On{}
                                                            case S{p15}:
                                                              match p15:
                                                                case Z{}: On{}
                                                                case S{p16}:
                                                                  match p16:
                                                                    case Z{}: On{}
                                                                    case S{p17}:
                                                                      match p17:
                                                                        case Z{}: On{}
                                                                        case S{p18}:
                                                                          match p18:
                                                                            case Z{}: On{}
                                                                            case S{p19}:
                                                                              match p19:
                                                                                case Z{}: On{}
                                                                                case S{p20}:
                                                                                  match p20:
                                                                                    case Z{}: On{}
                                                                                    case S{p21}:
                                                                                      match p21:
                                                                                        case Z{}: On{}
                                                                                        case S{p22}:
                                                                                          match p22:
                                                                                            case Z{}: On{}
                                                                                            case S{p23}:
                                                                                              match p23:
                                                                                                case Z{}: On{}
                                                                                                case S{p24}:
                                                                                                  match p24:
                                                                                                    case Z{}: On{}
                                                                                                    case S{p25}:
                                                                                                      match p25:
                                                                                                        case Z{}: On{}
                                                                                                        case S{p26}:
                                                                                                          match p26:
                                                                                                            case Z{}: On{}
                                                                                                            case S{p27}:
                                                                                                              match p27:
                                                                                                                case Z{}: On{}
                                                                                                                case S{p28}:
                                                                                                                  match p28:
                                                                                                                    case Z{}: On{}
                                                                                                                    case S{p29}:
                                                                                                                      match p29:
                                                                                                                        case Z{}: On{}
                                                                                                                        case S{p30}:
                                                                                                                          match p30:
                                                                                                                            case Z{}: On{}
                                                                                                                            case S{p31}:
                                                                                                                              match p31:
                                                                                                                                case Z{}: On{}
                                                                                                                                case S{p32}:
                                                                                                                                  match p32:
                                                                                                                                    case Z{}: On{}
                                                                                                                                    case S{p33}:
                                                                                                                                      match p33:
                                                                                                                                        case Z{}: On{}
                                                                                                                                        case S{p34}:
                                                                                                                                          match p34:
                                                                                                                                            case Z{}: On{}
                                                                                                                                            case S{p35}:
                                                                                                                                              match p35:
                                                                                                                                                case Z{}: On{}
                                                                                                                                                case S{p36}:
                                                                                                                                                  match p36:
                                                                                                                                                    case Z{}: On{}
                                                                                                                                                    case S{p37}:
                                                                                                                                                      match p37:
                                                                                                                                                        case Z{}: On{}
                                                                                                                                                        case S{p38}:
                                                                                                                                                          match p38:
                                                                                                                                                            case Z{}: On{}
                                                                                                                                                            case S{p39}:
                                                                                                                                                              match p39:
                                                                                                                                                                case Z{}: On{}
                                                                                                                                                                case S{p40}:
                                                                                                                                                                  match p40:
                                                                                                                                                                    case Z{}: On{}
                                                                                                                                                                    case S{p41}:
                                                                                                                                                                      match p41:
                                                                                                                                                                        case Z{}: On{}
                                                                                                                                                                        case S{p42}:
                                                                                                                                                                          match p42:
                                                                                                                                                                            case Z{}: On{}
                                                                                                                                                                            case S{p43}:
                                                                                                                                                                              match p43:
                                                                                                                                                                                case Z{}: On{}
                                                                                                                                                                                case S{p44}:
                                                                                                                                                                                  match p44:
                                                                                                                                                                                    case Z{}: On{}
                                                                                                                                                                                    case S{p45}:
                                                                                                                                                                                      match p45:
                                                                                                                                                                                        case Z{}: On{}
                                                                                                                                                                                        case S{p46}:
                                                                                                                                                                                          match p46:
                                                                                                                                                                                            case Z{}: On{}
                                                                                                                                                                                            case S{p47}:
                                                                                                                                                                                              match p47:
                                                                                                                                                                                                case Z{}: On{}
                                                                                                                                                                                                case S{p48}:
                                                                                                                                                                                                  match p48:
                                                                                                                                                                                                    case Z{}: On{}
                                                                                                                                                                                                    case S{p49}:
                                                                                                                                                                                                      match p49:
                                                                                                                                                                                                        case Z{}: On{}
                                                                                                                                                                                                        case S{p50}:
                                                                                                                                                                                                          match p50:
                                                                                                                                                                                                            case Z{}: On{}
                                                                                                                                                                                                            case S{p51}:
                                                                                                                                                                                                              match p51:
                                                                                                                                                                                                                case Z{}: On{}
                                                                                                                                                                                                                case S{p52}:
                                                                                                                                                                                                                  match p52:
                                                                                                                                                                                                                    case Z{}: On{}
                                                                                                                                                                                                                    case S{p53}:
                                                                                                                                                                                                                      match p53:
                                                                                                                                                                                                                        case Z{}: On{}
                                                                                                                                                                                                                        case S{p54}:
                                                                                                                                                                                                                          match p54:
                                                                                                                                                                                                                            case Z{}: On{}
                                                                                                                                                                                                                            case S{p55}:
                                                                                                                                                                                                                              match p55:
                                                                                                                                                                                                                                case Z{}: On{}
                                                                                                                                                                                                                                case S{p56}:
                                                                                                                                                                                                                                  match p56:
                                                                                                                                                                                                                                    case Z{}: On{}
                                                                                                                                                                                                                                    case S{p57}:
                                                                                                                                                                                                                                      match p57:
                                                                                                                                                                                                                                        case Z{}: On{}
                                                                                                                                                                                                                                        case S{p58}:
                                                                                                                                                                                                                                          match p58:
                                                                                                                                                                                                                                            case Z{}: On{}
                                                                                                                                                                                                                                            case S{p59}:
                                                                                                                                                                                                                                              match p59:
                                                                                                                                                                                                                                                case Z{}: On{}
                                                                                                                                                                                                                                                case S{p60}:
                                                                                                                                                                                                                                                  f(p1)
def main() -> Flag:
  f(S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{S{Z{}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}})
